import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { FaPlusCircle } from 'react-icons/fa';
import Sidebar from '../components/Sidebar';
import '../styles/settings.css';
import ApiService from '../services/apiClient';

const Settings2FA = () => {
    const [userEmail, setUserEmail] = useState('');
    const [userId, setUserId] = useState('');
    const [qrCode, setQrCode] = useState(null);
    const [token, setToken] = useState('');

    useEffect(() => {
        const fetchData = async () => {
          const user = localStorage.getItem('user');
          setUserId(JSON.parse(user)._id);
          setUserEmail(JSON.parse(user).email);
            try {
                const user = localStorage.getItem('user');
                const userObj = JSON.parse(user);
                const userId = userObj._id;
                const response = await ApiService.get2FAQrCode(userId);
                console.log('Fetched 2FA QR Code:', response);
                setQrCode(response.qrCodeDataURL);
            } catch (error) {
                console.error('Error fetching 2FA QR code:', error);
            }
        };
        
        fetchData();
    }, []);

    const handleVerify = async (token) => {
        try {
            const response = await ApiService.verify2FA(userId, token);
            console.log('2FA verification response:', response);
            localStorage.removeItem('user');
            localStorage.removeItem('token');
            localStorage.removeItem('login_response');
            window.location.href = '/login';
        } catch (error) {
            console.error('Error verifying 2FA code:', error);
        }
    };

    return (
      <div>
        <h1>Two-Factor Authentication Settings</h1>
        {qrCode ? (
          <div>
            <p>Scan this QR code with your authenticator app:</p>
            <img src={qrCode} alt="2FA QR Code" />
            <p>After scanning, enter the code generated by your app to verify and enable 2FA:</p>
            <input type="text" placeholder="Enter 2FA code" onChange={(e) => setToken(e.target.value)} />
            <button onClick={() => handleVerify(token)}>Verify</button>
          </div>
        ) : (
          <p>Loading QR code...</p>
        )}
      </div>
  );
};

export default Settings2FA;